version: '3.8'
services:
  app:
    image: movil-app-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GOOGLE.API.KEY=AIzaSyBZu4mfZMM75t20nO1zM0PwQoYMb_qKyU8


